<a href="https://colab.research.google.com/github/enrique-carbo/Data-Science/blob/main/Seccion14_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Random Forest

**Random Forest** es una combinación de árboles de desiciones, donde cada árbol selecciona una clase y luego se combinan la desiciones de cada árbol, para seleccionar una clase ganadora.  
Es uno de los *algoritmos de aprendizaje de clasificación* con mayor precisión.  
Funciona eficientemente en **bases de datos grandes**.  
Puede manejar cientos de variables de entrada.  


### Método de Clasificación. Random Forest

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


Cargamos un dataset en la variable "vinos"

In [2]:
vinos = pd.read_csv('https://raw.githubusercontent.com/enrique-carbo/data/main/vino.csv')
vinos.head(10)

Alcohol  Malic acid   Ash  ...  OD280/OD315 of diluted wines  Proline  Wine Type
0    14.23        1.71  2.43  ...                          3.92   1065.0        One
1    13.20        1.78  2.14  ...                          3.40   1050.0        One
2    13.16        2.36  2.67  ...                          3.17   1185.0        One
3    14.37        1.95  2.50  ...                          3.45   1480.0        One
4    13.24        2.59  2.87  ...                          2.93    735.0        One
5    14.20        1.76  2.45  ...                          2.85   1450.0        One
6    14.39        1.87  2.45  ...                          3.58   1290.0        One
7    14.06        2.15  2.61  ...                          3.58   1295.0        One
8    14.83        1.64  2.17  ...                          2.85   1045.0        One
9    13.86        1.35  2.27  ...                          3.55   1045.0        One

[10 rows x 14 columns]

In [ ]:
vinos.describe()

Alcohol  Malic acid  ...  OD280/OD315 of diluted wines      Proline
count  178.000000  178.000000  ...                    178.000000   178.000000
mean    13.000618    2.336348  ...                      2.611685   746.893258
std      0.811827    1.117146  ...                      0.709990   314.907474
min     11.030000    0.740000  ...                      1.270000   278.000000
25%     12.362500    1.602500  ...                      1.937500   500.500000
50%     13.050000    1.865000  ...                      2.780000   673.500000
75%     13.677500    3.082500  ...                      3.170000   985.000000
max     14.830000    5.800000  ...                      4.000000  1680.000000

[8 rows x 13 columns]

Vamos a separar en 2 variables; una denominada "X" las caracteristicas de los vinos y en la otra "y" el tipo del mismo (sería la columna a predecir)

"X" es todo el dataframe excepto la última columna.

In [3]:
X = vinos.drop('Wine Type', axis=1)
y = vinos['Wine Type']

In [4]:
from sklearn.model_selection import train_test_split 

Separamos las variables de entrenamiento y de test

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [14]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
randomforest = RandomForestClassifier(n_estimators=80)

Entrenamos el modelo con los datos de entrenamiento (X_train) y los valores objetivo de entrenamiento (y_train).

In [16]:
randomforest.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=80,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

El modelo ya esta entrenado.  
Crear las predicciones para los datos de test.

In [17]:
predicciones = randomforest.predict(X_test)

Visualizamos las predicciones

In [18]:
predicciones

array(['One', 'Three', 'One', 'One', 'Two', 'One', 'Two', 'Three', 'Two',
       'Three', 'Three', 'One', 'Three', 'Two', 'One', 'Three', 'Two',
       'Two', 'Three', 'Two', 'Two', 'Three', 'Two', 'Two', 'Three',
       'One', 'One', 'Three', 'One', 'One', 'Three', 'One', 'One',
       'Three', 'Three', 'Two', 'One', 'Three', 'Two', 'Two', 'Three',
       'One', 'Two', 'One', 'One', 'Three', 'Three', 'Three', 'Three',
       'Two', 'One', 'Two', 'Two', 'Two'], dtype=object)

In [19]:
y_test

51       One
83       Two
36       One
54       One
108      Two
33       One
127      Two
166    Three
109      Two
144    Three
157    Three
29       One
152    Three
114      Two
14       One
155    Three
122      Two
97       Two
133    Three
92       Two
63       Two
136    Three
101      Two
43       One
153    Three
4        One
20       One
135    Three
6        One
56       One
147    Three
35       One
28       One
140    Three
177    Three
113      Two
22       One
158    Three
104      Two
85       Two
165    Three
9        One
95       Two
46       One
15       One
148    Three
151    Three
171    Three
173    Three
123      Two
58       One
89       Two
76       Two
116      Two
Name: Wine Type, dtype: object

Vamos a evaluar el modelo para ver la precisión que posee.

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       1.00      0.94      0.97        18
       Three       0.95      1.00      0.97        18
         Two       0.94      0.94      0.94        18

    accuracy                           0.96        54
   macro avg       0.96      0.96      0.96        54
weighted avg       0.96      0.96      0.96        54



In [22]:
print(confusion_matrix(y_test, predicciones))

[[17  0  1]
 [ 0 18  0]
 [ 0  1 17]]
