<a href="https://colab.research.google.com/github/enrique-carbo/Data-Science/blob/main/Seccion13_Arboles_Desicion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Arboles de Desición  
Modelo de predicción utilizado en diversos ámbitos que van desde la inteligencia artificial hasta la economía.  
Dado un conjunto de datos, se fabrican diagramas de construcciones lógicas, que sirven para representar y categorizar una serie de condiciones que ocurren de forma sucesiva, para la resolución de un problema.



In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [ ]:
vinos = pd.read_csv('https://raw.githubusercontent.com/enrique-carbo/data/main/vino.csv')

In [ ]:
vinos.head(10)

Alcohol  Malic acid   Ash  ...  OD280/OD315 of diluted wines  Proline  Wine Type
0    14.23        1.71  2.43  ...                          3.92   1065.0        One
1    13.20        1.78  2.14  ...                          3.40   1050.0        One
2    13.16        2.36  2.67  ...                          3.17   1185.0        One
3    14.37        1.95  2.50  ...                          3.45   1480.0        One
4    13.24        2.59  2.87  ...                          2.93    735.0        One
5    14.20        1.76  2.45  ...                          2.85   1450.0        One
6    14.39        1.87  2.45  ...                          3.58   1290.0        One
7    14.06        2.15  2.61  ...                          3.58   1295.0        One
8    14.83        1.64  2.17  ...                          2.85   1045.0        One
9    13.86        1.35  2.27  ...                          3.55   1045.0        One

[10 rows x 14 columns]

In [ ]:
vinos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Alcohol                       178 non-null    float64
 1   Malic acid                    178 non-null    float64
 2   Ash                           178 non-null    float64
 3   Alcalinity of ash             178 non-null    float64
 4   Magnesium                     178 non-null    float64
 5   Total phenols                 178 non-null    float64
 6   Flavanoids                    178 non-null    float64
 7   Nonflavanoid phenols          178 non-null    float64
 8   Proanthocyanins               178 non-null    float64
 9   Color intensity               178 non-null    float64
 10  Hue                           178 non-null    float64
 11  OD280/OD315 of diluted wines  178 non-null    float64
 12  Proline                       178 non-null    float64
 13  Wine 

In [ ]:
vinos.shape

(178, 14)

In [ ]:
vinos.describe()

Alcohol  Malic acid  ...  OD280/OD315 of diluted wines      Proline
count  178.000000  178.000000  ...                    178.000000   178.000000
mean    13.000618    2.336348  ...                      2.611685   746.893258
std      0.811827    1.117146  ...                      0.709990   314.907474
min     11.030000    0.740000  ...                      1.270000   278.000000
25%     12.362500    1.602500  ...                      1.937500   500.500000
50%     13.050000    1.865000  ...                      2.780000   673.500000
75%     13.677500    3.082500  ...                      3.170000   985.000000
max     14.830000    5.800000  ...                      4.000000  1680.000000

[8 rows x 13 columns]

In [ ]:
vinos['Wine Type'].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [ ]:
vinos['Wine Type'].value_counts()

Two      71
One      59
Three    48
Name: Wine Type, dtype: int64

In [ ]:
X = vinos.drop('Wine Type', axis=1)
y = vinos['Wine Type']
y.shape, X.shape

((178,), (178, 13))

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
arbol = DecisionTreeClassifier()

In [ ]:
arbol.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
predicciones = arbol.predict(X_test)

In [ ]:
predicciones

array(['One', 'Two', 'Two', 'Two', 'Three', 'Two', 'Two', 'One', 'Three',
       'Three', 'One', 'One', 'Three', 'Two', 'Two', 'Three', 'Three',
       'Three', 'One', 'Two', 'Two', 'One', 'Two', 'Three', 'Three',
       'Three', 'Three', 'One', 'One', 'Three', 'Three', 'Three', 'Two',
       'One', 'One', 'Three', 'One', 'One', 'One', 'One', 'One', 'Three',
       'Three', 'Two', 'One', 'Three', 'Two', 'Three', 'Two', 'One',
       'Two', 'Three', 'Two', 'Three'], dtype=object)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       0.88      0.94      0.91        16
       Three       0.90      0.86      0.88        22
         Two       0.88      0.88      0.88        16

    accuracy                           0.89        54
   macro avg       0.89      0.89      0.89        54
weighted avg       0.89      0.89      0.89        54



In [ ]:
print(confusion_matrix(y_test, predicciones))

[[15  1  0]
 [ 1 19  2]
 [ 1  1 14]]
